# Generated by Django 5.1.6 on 2025-04-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_faculty_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='college_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
