# Generated by Django 5.1.6 on 2025-04-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_period_room_section_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='Section',
        ),
        migrations.AddField(
            model_name='section',
            name='sec_name',
            field=models.CharField(default='A', max_length=1, unique=True),
        ),
    ]
