# Generated by Django 5.1.6 on 2025-04-12 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_remove_section_section_section_sec_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='Period',
        ),
        migrations.AddField(
            model_name='period',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='period_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
