# Generated by Django 5.1.6 on 2025-04-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_email', models.EmailField(max_length=254, unique=True)),
                ('faculty_department', models.CharField(max_length=50)),
                ('subjects', models.ManyToManyField(related_name='faculties', to='Base_App.subject')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lab', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_App.day')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Base_App.faculty')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_App.period')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_App.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_App.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_App.subject')),
            ],
            options={
                'ordering': ['day', 'period'],
                'unique_together': {('faculty', 'day', 'period'), ('room', 'day', 'period'), ('section', 'day', 'period')},
            },
        ),
    ]
