# Generated by Django 5.1.6 on 2025-04-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0010_period_is_break'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_department',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_email',
        ),
        migrations.AddField(
            model_name='faculty',
            name='college_id',
            field=models.CharField(default='DSC-1000', max_length=25),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='sec_name',
            field=models.CharField(default='A', max_length=10, unique=True),
        ),
    ]
