# Generated by Django 5.1.6 on 2025-04-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='days',
            new_name='day',
        ),
    ]
