# Generated by Django 5.1.6 on 2025-04-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0005_remove_period_period_period_end_time_and_more'),
    ]

    operations = [
    ]
