# Generated by Django 5.1.6 on 2025-04-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0006_add_faculty_schedule'),
    ]

    operations = [
    ]
