# Generated by Django 5.1.6 on 2025-04-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0009_class_no_schedule_class_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
    ]
