# Generated by Django 5.1.6 on 2025-04-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0011_remove_faculty_faculty_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('faculty', 'day', 'period'), ('room', 'day', 'period')},
        ),
    ]
